### ISSUE TITLE
Navigation between pages is not vocalized by NVDA

### ISSUE THREAD

**Issue by GaetanBt** [GaetanBt/test-gatsby#1]

**Comment by GaetanBt** [comment]
https://github.com/gatsbyjs/gatsby/issues/5581

**Comment by PigeardSylvain** [comment]
I just test with NVDA, it does not say anything when changing pages.

**Comment by GaetanBt** [comment]
@PigeardSylvain I'm closing this since it seems that we won't use Gatsby for the project
